package simuladorliga.vista;

import java.util.*;
import javax.swing.*;
import simuladorliga.modelo.*;
import simuladorliga.persistencia.*;


public class CrearPanel extends javax.swing.JPanel {
    private MainFrame frame;
    private DefaultListModel<Equipo> modeloTodos;
    private DefaultListModel<Equipo> modeloSeleccionados;



    public CrearPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
            // Conectar el JScrollPane con la lista (por si NetBeans lo perdió)
        jScrollPane1.setViewportView(equiposListTodos);
        jScrollPane2.setViewportView(equiposListSeleccionados);
        modeloTodos = new DefaultListModel<>();
        modeloSeleccionados = new DefaultListModel<>();

        List<Equipo> equiposImportados = GestorFicheros.importarEquiposDesdeCSV();
        for (Equipo equipo : equiposImportados) {
            modeloTodos.addElement(equipo);
        }

        equiposListTodos.setModel(modeloTodos);
        equiposListSeleccionados.setModel(modeloSeleccionados);

        equiposListSeleccionados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        equiposListTodos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idaVueltaGroup = new javax.swing.ButtonGroup();
        botonCrear = new javax.swing.JButton();
        botonVolver1 = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        idaVueltaLabel = new javax.swing.JLabel();
        si = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        equiposListTodos = new javax.swing.JList<>();
        equiposLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        equiposListSeleccionados = new javax.swing.JList<>();
        todosEquiposLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 800));

        botonCrear.setText("CREAR LIGA");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });

        botonVolver1.setText("VOLVER");
        botonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolver1ActionPerformed(evt);
            }
        });

        nombreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreLabel.setText("Introduce el nombre de la liga:");

        campoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        idaVueltaLabel.setText("¿Joradas de ida y vuelta?");

        idaVueltaGroup.add(si);
        si.setText("SI");

        idaVueltaGroup.add(no);
        no.setText("No");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        equiposListTodos.setFixedCellHeight(25);
        jScrollPane1.setViewportView(equiposListTodos);

        equiposLabel.setText("Selecciona los equipos que deseas añadir a la liga:");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        equiposListSeleccionados.setFixedCellHeight(25);
        jScrollPane2.setViewportView(equiposListSeleccionados);

        todosEquiposLabel.setText("Lista de equipos");

        jLabel1.setText("Equipos añadidos");

        botonAgregar.setText("+ Añadir");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonQuitar.setText("- Quitar");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(botonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(todosEquiposLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(botonQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idaVueltaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(si)
                                .addGap(139, 139, 139)
                                .addComponent(no)))
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(equiposLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idaVueltaLabel)
                    .addComponent(si)
                    .addComponent(no))
                .addGap(32, 32, 32)
                .addComponent(equiposLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todosEquiposLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(botonAgregar)
                        .addGap(37, 37, 37)
                        .addComponent(botonQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        Equipo seleccionado = equiposListTodos.getSelectedValue();
        if (seleccionado != null && !modeloSeleccionados.contains(seleccionado)) {
            modeloSeleccionados.addElement(seleccionado);
            modeloTodos.removeElement(seleccionado);
        }
        
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        // TODO add your handling code here:
        Equipo seleccionado = equiposListSeleccionados.getSelectedValue();
        if (seleccionado != null) {
            modeloSeleccionados.removeElement(seleccionado);
            modeloTodos.addElement(seleccionado);
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        GestorBD gestor = new GestorBD();
        List<Equipo> equiposSeleccionados = new ArrayList<>();
        boolean idaVuelta = true;
        String nombreLiga = campoNombre.getText();
        
        for (int i = 0; i < modeloSeleccionados.getSize(); i++) {
            Equipo equipo = modeloSeleccionados.getElementAt(i);
            equiposSeleccionados.add(equipo);
        }
        
        
        if(equiposSeleccionados.size()<2){
            JOptionPane.showMessageDialog(frame, "No es posible crear una liga con menos de 2 equipos.");
            return;
        }
        
        if(nombreLiga == null || nombreLiga.trim().isEmpty()){
            JOptionPane.showMessageDialog(frame, "El nombre de la liga no puede estar vacío.");
            return;
        }
        if(no.isSelected())  idaVuelta = false;
        
        Liga liga = new Liga(nombreLiga, idaVuelta);
        liga.setEquipos(equiposSeleccionados);
        liga.generarCalendarioIdaVuelta();
        if (gestor.insertarLigaCompleta(liga)   ) {
            frame.irAMenuPanel();
        } else {
            JOptionPane.showMessageDialog(frame, "Error al crear la liga. Revisa los datos o intenta de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolver1ActionPerformed
        // TODO add your handling code here:
        frame.irAMenuPanel();
    }//GEN-LAST:event_botonVolver1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonVolver1;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel equiposLabel;
    private javax.swing.JList<Equipo> equiposListSeleccionados;
    private javax.swing.JList<Equipo> equiposListTodos;
    private javax.swing.ButtonGroup idaVueltaGroup;
    private javax.swing.JLabel idaVueltaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton no;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JRadioButton si;
    private javax.swing.JLabel todosEquiposLabel;
    // End of variables declaration//GEN-END:variables
}
