
package simuladorliga.vista;

import java.awt.*;
import javax.swing.*;
import simuladorliga.persistencia.*;
import java.util.List;
import simuladorliga.modelo.*;


public class MenuPanel extends javax.swing.JPanel {

     private MainFrame frame;

    public MenuPanel(MainFrame frame) {
        this.frame = frame;
        initComponents();
        
        //Cargamos nombres de las ligas 
        GestorBD gestor = new GestorBD();
        List<String> nombresLigas = gestor.obtenerNombresLigas(); 
        for (String nombre : nombresLigas) {
        comboLigas.addItem(nombre);
        }

        
        
        logoLabel.setHorizontalAlignment(SwingConstants.CENTER);
        logoLabel.setVerticalAlignment(SwingConstants.CENTER);
        
        ImageIcon logoOriginal = new ImageIcon(getClass().getResource("/imagenes/logo2.png"));
        //Imagen redimensionada adaptada al tamaño del JLabel
        Image logoEscalado = logoOriginal.getImage().getScaledInstance(567, 400, Image.SCALE_SMOOTH);
        logoLabel.setIcon(new ImageIcon(logoEscalado));
        titulo.setFont(new Font("Arial", Font.BOLD, 22));
        titulo.setAlignmentX(Component.CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        botonNuevaLiga = new javax.swing.JButton();
        botonCargarLiga = new javax.swing.JButton();
        comboLigas = new javax.swing.JComboBox<>();
        labelSeleccionaLiga = new javax.swing.JLabel();

        titulo.setText("¡BIENVENIDO AL SIMULADOR PARA LIGAS VIRTUALES!");

        botonNuevaLiga.setText("NUEVA LIGA");
        botonNuevaLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaLigaActionPerformed(evt);
            }
        });

        botonCargarLiga.setText("CARGAR LIGA");
        botonCargarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarLigaActionPerformed(evt);
            }
        });

        comboLigas.setToolTipText("");

        labelSeleccionaLiga.setText("Selecciona una liga existente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(botonNuevaLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCargarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelSeleccionaLiga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(comboLigas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo)
                .addGap(27, 27, 27)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSeleccionaLiga)
                .addGap(13, 13, 13)
                .addComponent(comboLigas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaLigaActionPerformed

    private void botonCargarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarLigaActionPerformed
        GestorBD gestor = new GestorBD();
        String nombreLigaSeleccionada = (String) comboLigas.getSelectedItem();
        if (nombreLigaSeleccionada != null) {
            int idLiga = gestor.obtenerIdLigaPorNombre(nombreLigaSeleccionada);
            Liga ligaRecuperada = gestor.recuperarLigaCompleta(idLiga);
            frame.setLiga(ligaRecuperada);
            frame.irAGestionPanel();
            
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una liga.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_botonCargarLigaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarLiga;
    private javax.swing.JButton botonNuevaLiga;
    private javax.swing.JComboBox<String> comboLigas;
    private javax.swing.JLabel labelSeleccionaLiga;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
